2021-09-25 10:39:18,772 __main__     INFO     START train.py
2021-09-25 10:39:18,773 __main__     INFO     Load train df
2021-09-25 10:39:21,016 __main__     INFO     Input shape: (279792, 77)
2021-09-25 10:39:21,162 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 10:39:21,377 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 10:39:21,378 __main__     INFO     Fit model
2021-09-25 10:39:21,378 raif_hack.model INFO     Fit lightgbm
2021-09-25 10:41:44,015 raif_hack.model INFO     Find corr coefficient
2021-09-25 10:41:44,990 raif_hack.model INFO     Corr coef: -0.12
2021-09-25 10:41:44,990 __main__     INFO     Save model
2021-09-25 10:42:46,495 __main__     INFO     Metrics stat for training data with offers prices: {'mape': 1.5204271589249925, 'mdape': 0.3125603548666643, 'rmse': 73946.13496006273, 'r2': 0.8172816627975483, 'raif_metric': 3.4943808614617957}
2021-09-25 10:42:47,487 __main__     INFO     Metrics stat for training data with manual prices: {'mape': 0.30544381035322893, 'mdape': 0.24759116446089766, 'rmse': 73135.9256925428, 'r2': 0.3308659827460806, 'raif_metric': 2.0449581821903826}
2021-09-25 10:42:47,487 __main__     INFO     END train.py
2021-09-25 11:24:33,028 __main__     INFO     START predict.py
2021-09-25 11:24:33,029 __main__     INFO     Load test df
2021-09-25 11:24:33,066 __main__     INFO     Input shape: (2974, 76)
2021-09-25 11:24:33,070 __main__     INFO     Load model
2021-09-25 11:24:33,147 __main__     INFO     Predict
2021-09-25 11:24:33,355 __main__     INFO     Save results
2021-09-25 11:24:33,367 __main__     INFO     END predict.py
2021-09-25 11:26:05,044 __main__     INFO     START predict.py
2021-09-25 11:26:05,046 __main__     INFO     Load test df
2021-09-25 11:26:05,053 __main__     INFO     Input shape: (2974, 2)
2021-09-25 11:26:05,060 __main__     ERROR    Traceback (most recent call last):
  File "predict.py", line 43, in <module>
    test_df = prepare_categorical(test_df)
  File "/root/baseline/raif_hack/features.py", line 12, in prepare_categorical
    df_new[fillna_cols] = df_new[fillna_cols].fillna(UNKNOWN_VALUE)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2912, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1298, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['region', 'city', 'street', 'realty_type'], dtype='object')] are in the [columns]"

2021-09-25 11:29:45,859 __main__     INFO     START predict.py
2021-09-25 11:29:45,860 __main__     INFO     Load test df
2021-09-25 11:29:48,035 __main__     INFO     Input shape: (279792, 77)
2021-09-25 11:29:48,159 __main__     INFO     Load model
2021-09-25 11:29:48,204 __main__     INFO     Predict
2021-09-25 11:30:05,843 __main__     INFO     Save results
2021-09-25 11:30:06,570 __main__     INFO     END predict.py
2021-09-25 12:14:00,029 __main__     INFO     START train.py
2021-09-25 12:14:00,030 __main__     INFO     Load train df
2021-09-25 12:14:02,282 __main__     INFO     Input shape: (279792, 77)
2021-09-25 12:14:02,414 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 12:14:02,625 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 12:14:02,625 __main__     INFO     Fit model
2021-09-25 12:14:02,625 raif_hack.model INFO     Fit lightgbm
2021-09-25 12:14:03,550 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 86, in fit
    model__categorical_feature=['67', '68', '69'])
  File "/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py", line 341, in fit
    Xt = self._fit(X, y, **fit_params_steps)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py", line 307, in _fit
    **fit_params_steps[name])
  File "/usr/local/lib/python3.6/dist-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 1105, in fit_transform
    return self.fit(X, sample_weight=sample_weight)._transform(X)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_kmeans.py", line 982, in fit
    accept_large_sparse=False)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 721, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

2021-09-25 12:43:30,777 __main__     INFO     START train.py
2021-09-25 12:43:30,778 __main__     INFO     Load train df
2021-09-25 12:43:33,017 __main__     INFO     Input shape: (279792, 77)
2021-09-25 12:43:33,146 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 12:43:33,353 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 12:43:33,353 __main__     INFO     Fit model
2021-09-25 12:43:33,353 raif_hack.model INFO     Fit lightgbm
2021-09-25 12:46:31,176 __main__     INFO     START train.py
2021-09-25 12:46:31,177 __main__     INFO     Load train df
2021-09-25 12:46:33,399 __main__     INFO     Input shape: (279792, 77)
2021-09-25 12:46:33,528 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 12:46:33,736 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 12:46:33,736 __main__     INFO     Fit model
2021-09-25 12:46:33,736 raif_hack.model INFO     Fit lightgbm
2021-09-25 13:12:24,319 __main__     INFO     START train.py
2021-09-25 13:12:24,320 __main__     INFO     Load train df
2021-09-25 13:12:26,524 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:12:26,660 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:12:26,881 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:12:26,904 __main__     INFO     Fit model
2021-09-25 13:12:26,904 raif_hack.model INFO     Fit nn
2021-09-25 13:12:26,907 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 121, in fit
    for i, (inputs, targets) in enumerate((X_offer, y_offer)):
ValueError: too many values to unpack (expected 2)

2021-09-25 13:14:05,432 __main__     INFO     START train.py
2021-09-25 13:14:05,433 __main__     INFO     Load train df
2021-09-25 13:14:07,713 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:14:07,848 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:14:08,071 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:14:08,072 __main__     INFO     Fit model
2021-09-25 13:14:08,072 raif_hack.model INFO     Fit nn
2021-09-25 13:14:08,075 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 121, in fit
    for inputs, targets in (X_offer, y_offer):
ValueError: too many values to unpack (expected 2)

2021-09-25 13:14:50,238 __main__     INFO     START train.py
2021-09-25 13:14:50,239 __main__     INFO     Load train df
2021-09-25 13:14:52,465 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:14:52,600 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:14:52,945 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:14:52,947 __main__     INFO     Fit model
2021-09-25 13:14:52,947 raif_hack.model INFO     Fit nn
2021-09-25 13:14:52,964 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 125, in fit
    yhat = self.model(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not str

2021-09-25 13:19:55,566 __main__     INFO     START train.py
2021-09-25 13:19:55,567 __main__     INFO     Load train df
2021-09-25 13:19:57,872 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:19:58,008 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:19:58,230 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:19:58,232 __main__     INFO     Fit model
2021-09-25 13:19:58,232 raif_hack.model INFO     Fit nn
2021-09-25 13:19:59,168 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 115, in fit
    X_offer, y_offer = self.preprocessor.fit_transform(X_offer, y_offer)
ValueError: too many values to unpack (expected 2)

2021-09-25 13:22:24,350 __main__     INFO     START train.py
2021-09-25 13:22:24,351 __main__     INFO     Load train df
2021-09-25 13:22:26,622 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:22:26,762 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:22:26,984 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:22:26,986 __main__     INFO     Fit model
2021-09-25 13:22:26,986 raif_hack.model INFO     Fit nn
2021-09-25 13:22:28,803 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 118, in fit
    X_offer, y_offer = self.preprocessor.fit_transform(X_offer, y_offer)
ValueError: too many values to unpack (expected 2)

2021-09-25 13:26:18,879 __main__     INFO     START train.py
2021-09-25 13:26:18,880 __main__     INFO     Load train df
2021-09-25 13:26:21,184 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:26:21,321 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:26:21,545 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:26:21,547 __main__     INFO     Fit model
2021-09-25 13:26:21,547 raif_hack.model INFO     Fit nn
2021-09-25 13:26:22,460 __main__     ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/__init__.py", line 374, in _get_column_indices
    all_columns = X.columns
AttributeError: 'numpy.ndarray' object has no attribute 'columns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 119, in fit
    X_manual = self.preprocessor.fit_transform(X_offer)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/compose/_column_transformer.py", line 505, in fit_transform
    self._validate_remainder(X)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/compose/_column_transformer.py", line 332, in _validate_remainder
    cols.extend(_get_column_indices(X, columns))
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/__init__.py", line 376, in _get_column_indices
    raise ValueError("Specifying the columns using strings is only "
ValueError: Specifying the columns using strings is only supported for pandas DataFrames

2021-09-25 13:34:39,910 __main__     INFO     START train.py
2021-09-25 13:34:39,911 __main__     INFO     Load train df
2021-09-25 13:34:42,165 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:34:42,299 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:34:42,518 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:34:42,520 __main__     INFO     Fit model
2021-09-25 13:34:42,520 raif_hack.model INFO     Fit nn
2021-09-25 13:34:43,444 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 129, in fit
    yhat = self.model(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

2021-09-25 13:37:23,703 __main__     INFO     START train.py
2021-09-25 13:37:23,704 __main__     INFO     Load train df
2021-09-25 13:37:25,977 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:37:26,112 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:37:26,331 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:37:26,332 __main__     INFO     Fit model
2021-09-25 13:37:26,332 raif_hack.model INFO     Fit nn
2021-09-25 13:37:27,293 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 129, in fit
    yhat = self.model(tensor(inputs))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Double but found Float

2021-09-25 13:43:52,031 __main__     INFO     START train.py
2021-09-25 13:43:52,032 __main__     INFO     Load train df
2021-09-25 13:43:54,281 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:43:54,417 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:43:54,637 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:43:54,639 __main__     INFO     Fit model
2021-09-25 13:43:54,639 raif_hack.model INFO     Fit nn
2021-09-25 13:43:55,580 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 130, in fit
    yhat = self.model(tensor(inputs).type(torch.DoubleTensor))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Double but found Float

2021-09-25 13:46:50,950 __main__     INFO     START train.py
2021-09-25 13:46:50,951 __main__     INFO     Load train df
2021-09-25 13:46:53,204 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:46:53,337 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:46:53,555 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:46:53,557 __main__     INFO     Fit model
2021-09-25 13:46:53,557 raif_hack.model INFO     Fit nn
2021-09-25 13:46:54,482 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 130, in fit
    print(self.model(tensor(inputs).type(torch.DoubleTensor)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Double but found Float

2021-09-25 13:47:24,781 __main__     INFO     START train.py
2021-09-25 13:47:24,782 __main__     INFO     Load train df
2021-09-25 13:47:27,009 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:47:27,143 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:47:27,361 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:47:27,362 __main__     INFO     Fit model
2021-09-25 13:47:27,362 raif_hack.model INFO     Fit nn
2021-09-25 13:47:28,328 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 131, in fit
    yhat = self.model(tensor(inputs).type(torch.DoubleTensor))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Double but found Float

2021-09-25 13:49:24,069 __main__     INFO     START train.py
2021-09-25 13:49:24,070 __main__     INFO     Load train df
2021-09-25 13:49:26,359 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:49:26,496 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:49:26,718 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:49:26,721 __main__     INFO     Fit model
2021-09-25 13:49:26,721 raif_hack.model INFO     Fit nn
2021-09-25 13:49:27,655 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 131, in fit
    yhat = self.model(tensor(inputs).type(torch.DoubleTensor))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Double but found Float

2021-09-25 13:50:16,526 __main__     INFO     START train.py
2021-09-25 13:50:16,527 __main__     INFO     Load train df
2021-09-25 13:50:18,770 __main__     INFO     Input shape: (279792, 77)
2021-09-25 13:50:18,905 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 13:50:19,124 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 13:50:19,126 __main__     INFO     Fit model
2021-09-25 13:50:19,126 raif_hack.model INFO     Fit nn
2021-09-25 13:50:20,062 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 131, in fit
    yhat = self.model(tensor(inputs).type(torch.DoubleTensor))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Double but found Float

2021-09-25 14:06:26,085 __main__     INFO     START train.py
2021-09-25 14:06:26,086 __main__     INFO     Load train df
2021-09-25 14:06:28,372 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:06:28,509 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:06:28,731 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:06:28,733 __main__     INFO     Fit model
2021-09-25 14:06:28,733 raif_hack.model INFO     Fit nn
2021-09-25 14:06:29,672 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 131, in fit
    yhat = self.model(torch.from_numpy(inputs).double)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not builtin_function_or_method

2021-09-25 14:13:09,990 __main__     INFO     START train.py
2021-09-25 14:13:09,991 __main__     INFO     Load train df
2021-09-25 14:13:12,247 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:13:12,391 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:13:12,616 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:13:12,621 __main__     INFO     Fit model
2021-09-25 14:13:12,621 raif_hack.model INFO     Fit nn
2021-09-25 14:13:13,555 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 131, in fit
    yhat = self.model(torch.from_numpy(inputs).double)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not builtin_function_or_method

2021-09-25 14:13:48,204 __main__     INFO     START train.py
2021-09-25 14:13:48,205 __main__     INFO     Load train df
2021-09-25 14:13:50,472 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:13:50,609 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:13:50,832 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:13:50,834 __main__     INFO     Fit model
2021-09-25 14:13:50,834 raif_hack.model INFO     Fit nn
2021-09-25 14:13:51,780 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 133, in fit
    loss = criterion(yhat, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 528, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 3079, in mse_loss
    if not (target.size() == input.size()):
AttributeError: 'float' object has no attribute 'size'

2021-09-25 14:18:00,693 __main__     INFO     START train.py
2021-09-25 14:18:00,694 __main__     INFO     Load train df
2021-09-25 14:18:03,000 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:18:03,137 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:18:03,360 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:18:03,362 __main__     INFO     Fit model
2021-09-25 14:18:03,362 raif_hack.model INFO     Fit nn
2021-09-25 14:18:04,287 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 136, in fit
    loss = criterion(yhat, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 528, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 3079, in mse_loss
    if not (target.size() == input.size()):
AttributeError: 'float' object has no attribute 'size'

2021-09-25 14:19:28,955 __main__     INFO     START train.py
2021-09-25 14:19:28,956 __main__     INFO     Load train df
2021-09-25 14:19:31,198 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:19:31,336 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:19:31,557 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:19:31,559 __main__     INFO     Fit model
2021-09-25 14:19:31,559 raif_hack.model INFO     Fit nn
2021-09-25 14:19:32,481 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 136, in fit
    loss = criterion(yhat[0], targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 528, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 3079, in mse_loss
    if not (target.size() == input.size()):
AttributeError: 'float' object has no attribute 'size'

2021-09-25 14:21:24,344 __main__     INFO     START train.py
2021-09-25 14:21:24,345 __main__     INFO     Load train df
2021-09-25 14:21:26,692 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:21:26,830 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:21:27,053 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:21:27,055 __main__     INFO     Fit model
2021-09-25 14:21:27,055 raif_hack.model INFO     Fit nn
2021-09-25 14:21:28,076 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 138, in fit
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Found dtype Float but expected Double

2021-09-25 14:22:23,907 __main__     INFO     START train.py
2021-09-25 14:22:23,908 __main__     INFO     Load train df
2021-09-25 14:22:26,190 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:22:26,327 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:22:26,549 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:22:26,552 __main__     INFO     Fit model
2021-09-25 14:22:26,552 raif_hack.model INFO     Fit nn
2021-09-25 14:22:27,515 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 138, in fit
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Found dtype Float but expected Double

2021-09-25 14:25:40,715 __main__     INFO     START train.py
2021-09-25 14:25:40,716 __main__     INFO     Load train df
2021-09-25 14:25:42,955 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:25:43,091 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:25:43,313 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:25:43,314 __main__     INFO     Fit model
2021-09-25 14:25:43,314 raif_hack.model INFO     Fit nn
2021-09-25 14:25:44,238 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 136, in fit
    loss = criterion(yhat.double, torch.tensor(targets).double)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 528, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 3079, in mse_loss
    if not (target.size() == input.size()):
AttributeError: 'builtin_function_or_method' object has no attribute 'size'

2021-09-25 14:30:42,646 __main__     INFO     START train.py
2021-09-25 14:30:42,647 __main__     INFO     Load train df
2021-09-25 14:30:44,963 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:30:45,099 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:30:45,322 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:30:45,324 __main__     INFO     Fit model
2021-09-25 14:30:45,324 raif_hack.model INFO     Fit nn
2021-09-25 14:30:46,251 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 136, in fit
    loss = criterion(yhat, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 528, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 3079, in mse_loss
    if not (target.size() == input.size()):
AttributeError: 'float' object has no attribute 'size'

2021-09-25 14:31:11,788 __main__     INFO     START train.py
2021-09-25 14:31:11,789 __main__     INFO     Load train df
2021-09-25 14:31:14,112 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:31:14,251 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:31:14,470 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:31:14,473 __main__     INFO     Fit model
2021-09-25 14:31:14,473 raif_hack.model INFO     Fit nn
2021-09-25 14:31:15,400 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 136, in fit
    loss = criterion(yhat, [targets])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 528, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 3079, in mse_loss
    if not (target.size() == input.size()):
AttributeError: 'list' object has no attribute 'size'

2021-09-25 14:31:46,816 __main__     INFO     START train.py
2021-09-25 14:31:46,818 __main__     INFO     Load train df
2021-09-25 14:31:49,054 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:31:49,189 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:31:49,406 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:31:49,407 __main__     INFO     Fit model
2021-09-25 14:31:49,407 raif_hack.model INFO     Fit nn
2021-09-25 14:31:50,347 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 138, in fit
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Found dtype Float but expected Double

2021-09-25 14:33:22,097 __main__     INFO     START train.py
2021-09-25 14:33:22,098 __main__     INFO     Load train df
2021-09-25 14:33:24,288 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:33:24,423 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:33:24,641 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:33:24,643 __main__     INFO     Fit model
2021-09-25 14:33:24,643 raif_hack.model INFO     Fit nn
2021-09-25 14:36:27,930 __main__     INFO     START train.py
2021-09-25 14:36:27,931 __main__     INFO     Load train df
2021-09-25 14:36:30,292 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:36:30,432 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:36:30,656 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:36:30,658 __main__     INFO     Fit model
2021-09-25 14:36:30,658 raif_hack.model INFO     Fit nn
2021-09-25 14:37:45,942 __main__     INFO     START train.py
2021-09-25 14:37:45,944 __main__     INFO     Load train df
2021-09-25 14:37:48,185 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:37:48,320 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:37:48,540 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:37:48,542 __main__     INFO     Fit model
2021-09-25 14:37:48,542 raif_hack.model INFO     Fit nn
2021-09-25 14:39:58,550 raif_hack.model INFO     Find corr coefficient
2021-09-25 14:39:58,554 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 143, in fit
    self._find_corr_coefficient(X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 87, in _find_corr_coefficient
    predictions = self.model(X_manual)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

2021-09-25 14:41:27,719 __main__     INFO     START train.py
2021-09-25 14:41:27,720 __main__     INFO     Load train df
2021-09-25 14:41:30,031 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:41:30,168 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:41:30,388 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:41:30,391 __main__     INFO     Fit model
2021-09-25 14:41:30,391 raif_hack.model INFO     Fit nn
2021-09-25 14:43:40,196 raif_hack.model INFO     Find corr coefficient
2021-09-25 14:43:40,215 __main__     ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/array_ops.py", line 143, in na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py", line 233, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py", line 119, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor.py", line 544, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
TypeError: rsub() received an invalid combination of arguments - got (Tensor, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, *, Number alpha)
 * (Tensor input, Number other, Number alpha)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 53, in <module>
    model.fit(X_offer, y_offer, X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 143, in fit
    self._find_corr_coefficient(X_manual, y_manual)
  File "/root/baseline/raif_hack/model.py", line 88, in _find_corr_coefficient
    deviation = ((y_manual - predictions) / predictions).median()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/__init__.py", line 343, in wrapper
    result = arithmetic_op(lvalues, rvalues, op)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/array_ops.py", line 190, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/array_ops.py", line 150, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/array_ops.py", line 112, in masked_arith_op
    result[mask] = op(xrav[mask], y)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor.py", line 544, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
TypeError: rsub() received an invalid combination of arguments - got (Tensor, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, *, Number alpha)
 * (Tensor input, Number other, Number alpha)


2021-09-25 14:48:24,646 __main__     INFO     START train.py
2021-09-25 14:48:24,647 __main__     INFO     Load train df
2021-09-25 14:48:26,942 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:48:27,077 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:48:27,296 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:48:27,298 __main__     INFO     Fit model
2021-09-25 14:48:27,298 raif_hack.model INFO     Fit nn
2021-09-25 14:50:38,137 raif_hack.model INFO     Find corr coefficient
2021-09-25 14:50:38,137 __main__     INFO     Save model
2021-09-25 14:50:38,142 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 155, in predict
    predictions = self.model(X)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not DataFrame

2021-09-25 14:55:09,837 __main__     INFO     START train.py
2021-09-25 14:55:09,838 __main__     INFO     Load train df
2021-09-25 14:56:12,163 __main__     INFO     START train.py
2021-09-25 14:56:12,164 __main__     INFO     Load train df
2021-09-25 14:56:14,491 __main__     INFO     Input shape: (279792, 77)
2021-09-25 14:56:14,627 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 14:56:14,848 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 14:56:14,850 __main__     INFO     Fit model
2021-09-25 14:56:14,850 raif_hack.model INFO     Fit nn
2021-09-25 14:58:24,403 raif_hack.model INFO     Find corr coefficient
2021-09-25 14:58:24,404 __main__     INFO     Save model
2021-09-25 14:58:24,932 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 156, in predict
    predictions = self.model(torch.tensor(X.values))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

2021-09-25 15:00:11,579 __main__     INFO     START train.py
2021-09-25 15:00:11,580 __main__     INFO     Load train df
2021-09-25 15:00:13,812 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:00:13,948 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:00:14,166 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:00:14,168 __main__     INFO     Fit model
2021-09-25 15:00:14,168 raif_hack.model INFO     Fit nn
2021-09-25 15:02:23,805 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:02:23,806 __main__     INFO     Save model
2021-09-25 15:02:23,911 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 156, in predict
    predictions = self.model(torch.tensor(X))
ValueError: could not determine the shape of object type 'DataFrame'

2021-09-25 15:03:46,185 __main__     INFO     START train.py
2021-09-25 15:03:46,186 __main__     INFO     Load train df
2021-09-25 15:03:48,460 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:03:48,594 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:03:48,812 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:03:48,813 __main__     INFO     Fit model
2021-09-25 15:03:48,814 raif_hack.model INFO     Fit nn
2021-09-25 15:05:58,467 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:05:58,468 __main__     INFO     Save model
2021-09-25 15:05:58,574 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 156, in predict
    predictions = self.model(torch.tensor([X]))
ValueError: could not determine the shape of object type 'DataFrame'

2021-09-25 15:07:33,063 __main__     INFO     START train.py
2021-09-25 15:07:33,064 __main__     INFO     Load train df
2021-09-25 15:07:35,310 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:07:35,445 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:07:35,664 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:07:35,666 __main__     INFO     Fit model
2021-09-25 15:07:35,666 raif_hack.model INFO     Fit nn
2021-09-25 15:09:45,269 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:09:45,270 __main__     INFO     Save model
2021-09-25 15:09:45,823 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 156, in predict
    predictions = self.model(torch.tensor(X.to_numpy()))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

2021-09-25 15:12:38,120 __main__     INFO     START train.py
2021-09-25 15:12:38,121 __main__     INFO     Load train df
2021-09-25 15:12:40,480 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:12:40,616 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:12:40,836 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:12:40,838 __main__     INFO     Fit model
2021-09-25 15:12:40,838 raif_hack.model INFO     Fit nn
2021-09-25 15:14:50,829 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:14:50,830 __main__     INFO     Save model
2021-09-25 15:14:51,391 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 156, in predict
    predictions = self.model(torch.from_numpy(X.to_numpy()))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

2021-09-25 15:20:37,466 __main__     INFO     START train.py
2021-09-25 15:20:37,467 __main__     INFO     Load train df
2021-09-25 15:20:39,755 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:20:39,890 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:20:40,108 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:20:40,109 __main__     INFO     Fit model
2021-09-25 15:20:40,110 raif_hack.model INFO     Fit nn
2021-09-25 15:22:53,491 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:22:53,492 __main__     INFO     Save model
2021-09-25 15:22:53,955 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 155, in predict
    print(self.model(torch.from_numpy(X.to_numpy())))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

2021-09-25 15:24:26,140 __main__     INFO     START train.py
2021-09-25 15:24:26,141 __main__     INFO     Load train df
2021-09-25 15:24:28,495 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:24:28,632 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:24:28,857 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:24:28,859 __main__     INFO     Fit model
2021-09-25 15:24:28,859 raif_hack.model INFO     Fit nn
2021-09-25 15:26:39,223 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:26:39,224 __main__     INFO     Save model
2021-09-25 15:26:39,667 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 155, in predict
    print(torch.from_numpy(X.to_numpy()))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

2021-09-25 15:30:28,367 __main__     INFO     START train.py
2021-09-25 15:30:28,368 __main__     INFO     Load train df
2021-09-25 15:30:30,662 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:30:30,797 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:30:31,015 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:30:31,017 __main__     INFO     Fit model
2021-09-25 15:30:31,017 raif_hack.model INFO     Fit nn
2021-09-25 15:32:38,916 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:32:38,917 __main__     INFO     Save model
2021-09-25 15:32:39,817 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 57, in <module>
    predictions_offer = model.predict(X_offer)
  File "/root/baseline/raif_hack/model.py", line 156, in predict
    print(torch.from_numpy(X.to_numpy()))
AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

2021-09-25 15:34:10,080 __main__     INFO     START train.py
2021-09-25 15:34:10,081 __main__     INFO     Load train df
2021-09-25 15:34:12,372 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:34:12,506 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:34:12,726 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:34:12,728 __main__     INFO     Fit model
2021-09-25 15:34:12,728 raif_hack.model INFO     Fit nn
2021-09-25 15:36:22,640 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:36:22,641 __main__     INFO     Save model
2021-09-25 15:36:23,567 __main__     ERROR    Traceback (most recent call last):
  File "train.py", line 58, in <module>
    metrics = metrics_stat(y_offer.values, predictions_offer/(1+model.corr_coef)) # для обучающей выборки с ценами из объявлений смотрим качество без коэффициента
  File "/root/baseline/raif_hack/metrics.py", line 36, in metrics_stat
    mape = mean_absolute_percentage_error(y_true, y_pred)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_regression.py", line 258, in mean_absolute_percentage_error
    y_true, y_pred, multioutput)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_regression.py", line 90, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 673, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor.py", line 643, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

2021-09-25 15:39:03,364 __main__     INFO     START train.py
2021-09-25 15:39:03,365 __main__     INFO     Load train df
2021-09-25 15:39:05,741 __main__     INFO     Input shape: (279792, 77)
2021-09-25 15:39:05,878 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 15:39:06,100 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 15:39:06,102 __main__     INFO     Fit model
2021-09-25 15:39:06,102 raif_hack.model INFO     Fit nn
2021-09-25 15:41:17,381 raif_hack.model INFO     Find corr coefficient
2021-09-25 15:41:17,382 __main__     INFO     Save model
2021-09-25 15:41:17,383 __main__     INFO     END train.py
2021-09-25 15:44:35,414 __main__     INFO     START predict.py
2021-09-25 15:44:35,415 __main__     INFO     Load test df
2021-09-25 15:44:35,454 __main__     INFO     Input shape: (2974, 76)
2021-09-25 15:44:35,458 __main__     INFO     Load model
2021-09-25 15:44:35,462 __main__     ERROR    Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    model = BenchmarkModel.load(args['mp'])
  File "/root/baseline/raif_hack/model.py", line 187, in load
    model.load_state_dict(load(path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BenchmarkModel:
	Missing key(s) in state_dict: "hidden1.weight", "hidden1.bias", "hidden2.weight", "hidden2.bias", "hidden3.weight", "hidden3.bias", "model.0.weight", "model.0.bias", "model.2.weight", "model.2.bias", "model.4.weight", "model.4.bias". 
	Unexpected key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "4.weight", "4.bias". 

2021-09-25 17:38:07,851 __main__     INFO     START predict.py
2021-09-25 17:38:07,852 __main__     INFO     Load test df
2021-09-25 17:38:07,887 __main__     INFO     Input shape: (2974, 76)
2021-09-25 17:38:07,891 __main__     INFO     Load model
2021-09-25 17:38:07,894 __main__     ERROR    Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    model = BenchmarkModel.load(args['mp'])
  File "/root/baseline/raif_hack/model.py", line 187, in load
    model.load_state_dict(load(path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BenchmarkModel:
	Missing key(s) in state_dict: "hidden1.weight", "hidden1.bias", "hidden2.weight", "hidden2.bias", "hidden3.weight", "hidden3.bias", "model.0.weight", "model.0.bias", "model.2.weight", "model.2.bias", "model.4.weight", "model.4.bias". 
	Unexpected key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "4.weight", "4.bias". 

2021-09-25 17:50:26,538 __main__     INFO     START train.py
2021-09-25 17:50:26,539 __main__     INFO     Load train df
2021-09-25 17:50:26,574 __main__     INFO     Input shape: (2974, 76)
2021-09-25 17:50:26,581 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 17:50:26,589 __main__     ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'per_square_meter_price'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 46, in <module>
    y_offer = train_df[train_df.price_type == PriceTypeEnum.OFFER_PRICE][TARGET]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'per_square_meter_price'

2021-09-25 17:51:46,270 __main__     INFO     START train.py
2021-09-25 17:51:46,271 __main__     INFO     Load train df
2021-09-25 17:51:46,309 __main__     INFO     Input shape: (2974, 76)
2021-09-25 17:51:46,316 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 17:51:46,321 __main__     ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'per_square_meter_price'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 46, in <module>
    y_offer = train_df[train_df.price_type == PriceTypeEnum.OFFER_PRICE][TARGET]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'per_square_meter_price'

2021-09-25 17:56:32,845 __main__     INFO     START train.py
2021-09-25 17:56:32,846 __main__     INFO     Load train df
2021-09-25 17:56:35,026 __main__     INFO     Input shape: (279792, 77)
2021-09-25 17:56:35,161 numexpr.utils INFO     NumExpr defaulting to 4 threads.
2021-09-25 17:56:35,380 __main__     INFO     X_offer (275299, 70)  y_offer (275299,)	X_manual (4493, 70) y_manual (4493,)
2021-09-25 17:56:35,381 __main__     INFO     Fit model
2021-09-25 17:56:35,382 raif_hack.model INFO     Fit nn
2021-09-25 17:58:42,815 raif_hack.model INFO     Find corr coefficient
2021-09-25 17:58:42,816 __main__     INFO     Save model
2021-09-25 17:58:42,818 __main__     INFO     END train.py
2021-09-25 18:01:00,523 __main__     INFO     START predict.py
2021-09-25 18:01:00,524 __main__     INFO     Load test df
2021-09-25 18:01:02,722 __main__     INFO     Input shape: (279792, 77)
2021-09-25 18:01:02,853 __main__     INFO     Load model
2021-09-25 18:01:02,857 __main__     ERROR    Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    model = BenchmarkModel.load(args['mp'])
  File "/root/baseline/raif_hack/model.py", line 187, in load
    model.load_state_dict(load(path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BenchmarkModel:
	Missing key(s) in state_dict: "hidden1.weight", "hidden1.bias", "hidden2.weight", "hidden2.bias", "hidden3.weight", "hidden3.bias", "model.0.weight", "model.0.bias", "model.2.weight", "model.2.bias", "model.4.weight", "model.4.bias". 
	Unexpected key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "4.weight", "4.bias". 

2021-09-25 18:10:09,384 __main__     INFO     START predict.py
2021-09-25 18:10:09,385 __main__     INFO     Load test df
2021-09-25 18:10:09,421 __main__     INFO     Input shape: (2974, 76)
2021-09-25 18:10:09,424 __main__     INFO     Load model
2021-09-25 18:10:09,425 __main__     ERROR    Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    model = BenchmarkModel.load(args['mp'])
  File "/root/baseline/raif_hack/model.py", line 184, in load
    model = pickle.load(f)
NameError: name 'pickle' is not defined

2021-09-25 18:13:53,315 __main__     INFO     START predict.py
2021-09-25 18:13:53,316 __main__     INFO     Load test df
2021-09-25 18:13:53,350 __main__     INFO     Input shape: (2974, 76)
2021-09-25 18:13:53,355 __main__     INFO     Load model
2021-09-25 18:13:53,355 __main__     ERROR    Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    model = BenchmarkModel.load(args['mp'])
  File "/root/baseline/raif_hack/model.py", line 185, in load
    model = pickle.load(f)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

2021-09-25 18:22:13,727 __main__     INFO     START predict.py
2021-09-25 18:22:13,728 __main__     INFO     Load test df
2021-09-25 18:22:13,762 __main__     INFO     Input shape: (2974, 76)
2021-09-25 18:22:13,767 __main__     INFO     Load model
2021-09-25 18:22:13,770 __main__     ERROR    Traceback (most recent call last):
  File "predict.py", line 46, in <module>
    model = BenchmarkModel.load(args['mp'])
  File "/root/baseline/raif_hack/model.py", line 188, in load
    model.load_state_dict(torch.load(path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BenchmarkModel:
	Missing key(s) in state_dict: "hidden1.weight", "hidden1.bias", "hidden2.weight", "hidden2.bias", "hidden3.weight", "hidden3.bias", "model.0.weight", "model.0.bias", "model.2.weight", "model.2.bias", "model.4.weight", "model.4.bias". 
	Unexpected key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "4.weight", "4.bias". 

